run:
  name: "arxiv-test"
  seed: 42
  log: true
  dataset: "ogbn-arxiv"
  resume: false
  checkpoint_path:
  test_only: false

train:
  gpus: 1
  epochs: 500
  num_workers: 32

model:
  depth: 3
  logits_dim: 40
  attn_dropout: 0.1
  ff_dropout: 0.1
  gnn_embed_dim: 256
  num_latents: 32
  latent_dim: 128
  cross_heads: 4
  latent_heads: 4
  cross_dim_head: 4
  latent_dim_head: 4
  lr: 0.0005
  weight_tie_layers: false
  
