run:
  name: "cham"
  seed: 1334
  log: true
  dataset: "cora"
  resume: false
  checkpoint_path: 
  test_only: false

train:
  gpus: 1
  epochs: 1000
  num_workers: 32

model:
  depth: 2
  logits_dim: 5
  queries_dim: 32
  attn_dropout: 0
  ff_dropout: 0
  gnn_embed_dim: 512
  num_latents: 8
  latent_dim: 16
  cross_heads: 4
  latent_heads: 4
  cross_dim_head: 4
  latent_dim_head: 4
  lr: 0.005
  
