run:
  name: "circles"
  seed: 99
  log: true
  dataset: "circles"
  resume: false
  checkpoint_path: 
  test_only: false

train:
  gpus: 1
  epochs: 200
  num_workers: 32

model:
  depth: 1
  logits_dim: 4
  attn_dropout: 0.0
  ff_dropout: 0.0
  gnn_embed_dim: 256
  num_latents: 128
  latent_dim: 32
  cross_heads: 4
  latent_heads: 4
  cross_dim_head: 8
  latent_dim_head: 8
  lr: 0.001
  
