run:
  name: "cora+gcnonly"
  seed: 42
  log: true
  dataset: "cora"
  resume: false
  checkpoint_path: 
  test_only: false

train:
  gpus: 1
  epochs: 1000
  num_workers: 32

model:
  depth: 1
  logits_dim: 7
  attn_dropout: 0
  ff_dropout: 0
  gnn_embed_dim: 16
  num_latents: 3
  latent_dim: 8
  cross_heads: 8
  latent_heads: 8
  cross_dim_head: 8
  latent_dim_head: 8
  lr: 0.0005
  
