run:

  name: "bigger"
  seed: 42
  log: true
  dataset: "ogbg-molhiv"
  test: true
  resume: false
  checkpoint_path: 

  batch_size: 128

train:
  gpus: 1
  epochs: 100
  num_workers: 32

model:
  input_channels: 64
  depth: 4
  attn_dropout: 0.1
  ff_dropout: 0.1
  weight_tie_layers: false
  virtual_latent: true
  gnn_embed_dim: 256
  num_latents: 12
  latent_dim: 200
  cross_heads: 8
  latent_heads: 8
  cross_dim_head: 8
  latent_dim_head: 8
  loss_fn: "bce"
  lr: 0.0001
  
