run:
  seed: 42
  log: true
  dataset: "ogbg-molpcba"
  name: "test"
  test: true
  resume: false
  checkpoint_path: 

  batch_size_train: 256
  batch_size_val: 256
  batch_size_test: 256

train:
  gpus: 1
  epochs: 100
  num_workers: 32

model:
  depth: 4
  ff_dropout: 0.1
  attn_dropout: 0.1
  gnn_dropout: 0.1
  gnn_embed_dim: 300
  queries_dim: 256
  num_gnn_layers: 4
  num_latents: 16
  latent_dim: 256
  cross_dim_head: 64
  latent_dim_head: 64
  weight_tie_layers: false
  loss_fn: "bce"
  gnn_type: "gin-virtual"
  lr: 0.0001
