run:
  name: ""
  seed: 42
  log: false
  dataset: "ogbn-proteins"
  resume: false
  checkpoint_path: "outputs/2022-05-16/proteins_seed99/checkpoints/epoch_epoch=2489.ckpt"
  test_only: true

train:
  gpus: 1
  epochs: 2500
  num_workers: 32

model:
  depth: 1
  queries_dim: 256
  logits_dim: 112
  attn_dropout: 0.0
  ff_dropout: 0.0
  gnn_embed_dim: 256
  num_latents: 512
  latent_dim: 128
  cross_heads: 4
  latent_heads: 8
  cross_dim_head: 8
  latent_dim_head: 8
  lr: 0.0001