run:
  name: "sage+transformer+noconcat"
  seed: 1
  log: true
  dataset: "ogbn-proteins"
  resume: false
  checkpoint_path: outputs/2022-04-25/12-13-40/checkpoints/last.ckpt
  test_only: false

train:
  gpus: 1
  epochs: 1000
  num_workers: 32

model:
  depth: 3
  logits_dim: 112
  attn_dropout: 0.0
  ff_dropout: 0.0
  gnn_embed_dim: 256
  num_latents: 256
  latent_dim: 128
  cross_heads: 4
  latent_heads: 4
  cross_dim_head: 8
  latent_dim_head: 8
  lr: 0.001
  
