run:
  name: "reproduce_mat_sage"
  seed: 1337
  log: true
  dataset: "ogbn-proteins"
  resume: false
  checkpoint_path:
  test_only: false


train:
  gpus: 1
  epochs: 1000
  num_workers: 32

model:
  
  depth: 1
  logits_dim: 112
  attn_dropout: 0.0
  ff_dropout: 0.1
  gnn_embed_dim: 256
  num_latents: 512
  latent_dim: 32
  cross_heads: 4
  latent_heads: 4
  cross_dim_head: 8
  latent_dim_head: 8
  lr: 0.0001
  
